"""Add IngestJob and FactsLedger

Revision ID: ec7386d2401e
Revises: 004
Create Date: 2025-12-01 18:11:47.587285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec7386d2401e'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_jobs',
    sa.Column('job_id', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_ingest_jobs_status'), 'ingest_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_ingest_jobs_tenant_id'), 'ingest_jobs', ['tenant_id'], unique=False)
    op.create_table('facts_ledger',
    sa.Column('ledger_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decisions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unresolved_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.thread_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ledger_id')
    )
    op.create_index(op.f('ix_facts_ledger_tenant_id'), 'facts_ledger', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_facts_ledger_thread_id'), 'facts_ledger', ['thread_id'], unique=True)
    op.alter_column('attachments', 'status',
               existing_type=postgresql.ENUM('pending', 'parsed', 'unparsed_password_protected', 'failed', name='attachment_status'),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('attachments', 'extracted_chars',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attachments', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('audit_log', 'risk_level',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='risk_level'),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('audit_log', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.alter_column('chunks', 'chunk_type',
               existing_type=postgresql.ENUM('message_body', 'attachment_text', 'attachment_table', 'quoted_history', 'other', name='chunk_type'),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('chunks', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('chunks', 'section_path',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('chunks', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chunks', 'char_start',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chunks', 'char_end',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chunks', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_chunks_fts'), table_name='chunks', postgresql_using='gin')
    # op.create_index('ix_chunks_embedding', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_chunks_tsv_text', 'chunks', ['tsv_text'], unique=False, postgresql_using='gin')
    op.alter_column('messages', 'to_addrs',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    op.alter_column('messages', 'cc_addrs',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    op.alter_column('messages', 'bcc_addrs',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    op.alter_column('messages', 'has_quoted_mask',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('messages', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_messages_fts'), table_name='messages', postgresql_using='gin')
    op.create_index('ix_messages_tsv_subject_body', 'messages', ['tsv_subject_body'], unique=False, postgresql_using='gin')
    op.alter_column('threads', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('threads', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('ix_messages_tsv_subject_body', table_name='messages', postgresql_using='gin')
    op.create_index(op.f('idx_messages_fts'), 'messages', ['tsv_subject_body'], unique=False, postgresql_using='gin')
    op.alter_column('messages', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('messages', 'has_quoted_mask',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('messages', 'bcc_addrs',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    op.alter_column('messages', 'cc_addrs',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    op.alter_column('messages', 'to_addrs',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    op.drop_index('ix_chunks_tsv_text', table_name='chunks', postgresql_using='gin')
    # op.drop_index('ix_chunks_embedding', table_name='chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('idx_chunks_fts'), 'chunks', ['tsv_text'], unique=False, postgresql_using='gin')
    op.alter_column('chunks', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('chunks', 'char_end',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chunks', 'char_start',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chunks', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chunks', 'section_path',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chunks', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chunks', 'chunk_type',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('message_body', 'attachment_text', 'attachment_table', 'quoted_history', 'other', name='chunk_type'),
               nullable=True)
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.alter_column('audit_log', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('audit_log', 'risk_level',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('low', 'medium', 'high', name='risk_level'),
               nullable=True)
    op.alter_column('attachments', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('attachments', 'extracted_chars',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('attachments', 'status',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('pending', 'parsed', 'unparsed_password_protected', 'failed', name='attachment_status'),
               nullable=True)
    op.drop_index(op.f('ix_facts_ledger_thread_id'), table_name='facts_ledger')
    op.drop_index(op.f('ix_facts_ledger_tenant_id'), table_name='facts_ledger')
    op.drop_table('facts_ledger')
    op.drop_index(op.f('ix_ingest_jobs_tenant_id'), table_name='ingest_jobs')
    op.drop_index(op.f('ix_ingest_jobs_status'), table_name='ingest_jobs')
    op.drop_table('ingest_jobs')
    # ### end Alembic commands ###
